name: My Action
on:
  workflow_dispatch:
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - name: My Action
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/test-org12333/fdsfsfe/pages \
            -d '{"source":{"branch":"main","path":"/docs"}}'
